'use strict';
require('../scss/index.scss');
require('../index.html');
// require('./ajax.js');
// require('./one.js');
// require('./two.js');
// require('./react.js');
// require('./main.js');
// require('./redux.js');
require('./redux_middleware.js');
